// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKu9aA60cAt4qvm9m63hPIIryYMQOHXgo',
    appId: '1:285724819496:web:aec9d12d0eba297b13b51d',
    messagingSenderId: '285724819496',
    projectId: 'purecuts-11a7c',
    authDomain: 'purecuts-11a7c.firebaseapp.com',
    storageBucket: 'purecuts-11a7c.firebasestorage.app',
    measurementId: 'G-Z9ET3XEDX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr3R1QgYZcZcF9DxjsrVwkqSQ34idV8po',
    appId: '1:285724819496:android:3d78f0519383df4b13b51d',
    messagingSenderId: '285724819496',
    projectId: 'purecuts-11a7c',
    storageBucket: 'purecuts-11a7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKimuCjKj2bjgIybLBiPQ4d7vQJrDBrW0',
    appId: '1:285724819496:ios:2237a1daf659b7e913b51d',
    messagingSenderId: '285724819496',
    projectId: 'purecuts-11a7c',
    storageBucket: 'purecuts-11a7c.firebasestorage.app',
    iosBundleId: 'com.example.purecuts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKimuCjKj2bjgIybLBiPQ4d7vQJrDBrW0',
    appId: '1:285724819496:ios:2237a1daf659b7e913b51d',
    messagingSenderId: '285724819496',
    projectId: 'purecuts-11a7c',
    storageBucket: 'purecuts-11a7c.firebasestorage.app',
    iosBundleId: 'com.example.purecuts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKu9aA60cAt4qvm9m63hPIIryYMQOHXgo',
    appId: '1:285724819496:web:7eb61df6e98ff97113b51d',
    messagingSenderId: '285724819496',
    projectId: 'purecuts-11a7c',
    authDomain: 'purecuts-11a7c.firebaseapp.com',
    storageBucket: 'purecuts-11a7c.firebasestorage.app',
    measurementId: 'G-SDP5DLHV2E',
  );
}
